/**
 * Sample products for the Product Master — two machines so the table, the
 * sectioned form and the detail pane have realistic content on first load.
 */

import type { ProductRecord, ProductSubmoduleKey } from "./types";

function stamp(
  submodule: ProductSubmoduleKey,
  rows: Array<Record<string, unknown>>,
): ProductRecord[] {
  return rows.map((r, i) => ({
    ...r,
    id: `prodseed_${submodule}_${i + 1}`,
    submodule,
    createdAt: "2026-06-01T09:00:00.000Z",
    updatedAt: "2026-06-01T09:00:00.000Z",
  })) as ProductRecord[];
}

const PRODUCT_SEED: Array<Record<string, unknown>> = [
  {
    docNo: "PRD-CUP-2001",
    productCategory: "Paper Cup Machine",
    productName: "High-Speed Paper Cup Machine",
    nesscoModelNo: "NC-HS-2001",
    variant: "High Speed",
    modelPrefix: "NC",
    status: "ACTIVE",
    hsnCode: "8441",
    machineSpeed: 160,
    stableSpeed: 140,
    uomSpeed: "Cups/min",
    weightKg: 2200,
    powerKw: 18,
    p1Dimension: 3200,
    p2Dimension: 1800,
    p3Dimension: 1900,
    websiteDisplayStatus: "YES",
    internalRemark: "Flagship high-speed model.",
    bottomDiaMin: 40,
    bottomDiaMax: 80,
    topDiaMin: 50,
    topDiaMax: 90,
    heightMin: 60,
    heightMax: 135,
    knurlingDepthMax: 2,
    otherSpecifications: "Ultrasonic + hot-air sealing; servo-driven knurling.",
    overallSpecifications: "50–90 ml to 350 ml cup range.",
    productWeightKgs: 2400,
    noOfPackages: 3,
    package1: "3300 x 1300 x 2000",
    package2: "1500 x 1200 x 1400",
    dispatchP1: "3300 x 1300 x 2000",
    domesticPriceMin: 1800000,
    domesticPriceMax: 2200000,
    domesticPriceAvg: 2000000,
    domesticPricingRemarks: "Ex-works Jaipur; GST extra.",
    exportPriceMin: 24000,
    exportPriceMax: 28000,
    exportPriceAvg: 26000,
    exportPricingRemarks: "FOB Mundra (USD).",
    currency: "USD",
    salesChannel: "BOTH",
    youtubeLink: "https://youtu.be/example-cup-2001",
    defaultAddOns: "Auto stacker; air compressor 5 HP",
    operatingVoltage: "415V",
    phaseRequirement: "3P",
    startingLoadKw: 22,
    runningLoadKw: 16,
    stabilizerLoadKva: 30,
    airFlowRate: 12,
    airFlowUom: "CFM",
    airPressure: 6,
    airPressureUom: "bar",
    workingDimBasic: "12 x 8 x 7",
    workingDimTop: "16 x 10 x 7",
    technicalRemarks: "Requires dry, oil-free air supply.",
    oemCode: "OEM-CUP-X1",
    oemModelNo: "X1-160",
    oemPhaseRequirement: "3P",
    swSpeed: "160",
    swPowerDetails: "18 kW",
    routes: "Assembly → QC → Packing",
    isr: "Rahul Verma",
  },
  {
    docNo: "PRD-GLS-3010",
    productCategory: "Paper Glass Machine",
    productName: "Paper Glass Forming Machine",
    nesscoModelNo: "NG-3010",
    variant: "Standard",
    modelPrefix: "NG",
    status: "ACTIVE",
    hsnCode: "8441",
    machineSpeed: 110,
    stableSpeed: 95,
    uomSpeed: "Pieces/min",
    weightKg: 1600,
    powerKw: 12,
    p1Dimension: 2600,
    p2Dimension: 1500,
    p3Dimension: 1750,
    websiteDisplayStatus: "YES",
    bottomDiaMin: 35,
    bottomDiaMax: 60,
    topDiaMin: 45,
    topDiaMax: 75,
    heightMin: 70,
    heightMax: 110,
    knurlingDepthMax: 1.5,
    productWeightKgs: 1750,
    noOfPackages: 2,
    package1: "2700 x 1100 x 1900",
    domesticPriceMin: 950000,
    domesticPriceMax: 1150000,
    domesticPriceAvg: 1050000,
    currency: "USD",
    salesChannel: "DOMESTIC",
    operatingVoltage: "415V",
    phaseRequirement: "3P",
    startingLoadKw: 15,
    runningLoadKw: 11,
    stabilizerLoadKva: 20,
    airFlowRate: 8,
    airFlowUom: "CFM",
    airPressure: 6,
    airPressureUom: "bar",
    workingDimBasic: "10 x 7 x 7",
    technicalRemarks: "Standard production model.",
    routes: "Assembly → QC → Packing",
    isr: "Sneha Rao",
  },
];

const SEED_BY_KEY: Record<ProductSubmoduleKey, Array<Record<string, unknown>>> = {
  product: PRODUCT_SEED,
};

export function seedRecords(key: ProductSubmoduleKey): ProductRecord[] {
  return stamp(key, SEED_BY_KEY[key]);
}
